---
name: Static Analysis

on:
  push:
    branches: [main]
  pull_request:

jobs:
  standard-js:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
          cache: 'npm'
      - run: npm ci
      - run: npm run lint:js

  solhint:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
          cache: 'npm'
      - run: npm ci
      - run: npm run lint:solidity
